version: "3"
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /MySQL/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: develop
            MYSQL_PASSWORD: develop
