version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
        command: echo "Circle CI Test"
workflows:
  build:
    jobs:
      - test:
        pre-steps:
          - run:
            command: echo "Pre Step"
        post-steps:
          - run:
            command: echo "Post Step"
