@startuml Structure
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/GroupIcons/Cloud.puml
!includeurl AWSPuml/GroupIcons/Region.puml
!includeurl AWSPuml/GroupIcons/VirtualPrivateCloudVPC.puml
!includeurl AWSPuml/GroupIcons/VPCSubnetPrivate.puml
!includeurl AWSPuml/GroupIcons/VPCSubnetPublic.puml
!includeurl AWSPuml/Database/RDS.puml
!includeurl AWSPuml/Compute/EC2.puml
!includeurl AWSPuml/Compute/EC2ContainerRegistry.puml
!includeurl AWSPuml/Compute/EC2ContainerRegistryImage.puml
!includeurl AWSPuml/Compute/ElasticContainerService.puml

!include ./AwsIconsForPlantUML_Helper.puml

Cloud(Cloud, AWS, "AWS Cloud") {
    Region(Region, ap-northeast-1, "Asia/Tokyo") {
        VirtualPrivateCloudVPC(VPC, VPC, "10.0.0.0/21") {
            AvailabilityZone(AZ_1a, "1a") {
                VPCSubnetPublic(Subnet1a_1, Public, "10.0.1.0/24") {
                    EC2(SSHServer, EC2, "SSHサーバ")
                }
                VPCSubnetPrivate(Subnet1a_2, Private, "10.0.2.0/24") {
                    RDS(DB1, RDS, "MySQL")
                    ElasticContainerService(ECS, ECS, "ECS")
                }
            }
            AvailabilityZone(AZ_1c, "1c") {
                VPCSubnetPrivate(Subnet1c_1, Private, "10.0.3.0/24") {
                    RDS(DB2, RDS, "MySQL")
                }
            }
        }
    }

    EC2ContainerRegistry(ECR, ECR, "ECR") {
        EC2ContainerRegistryImage(InnerAPI_Image, "Container", "InnerAPI")
    }
}

ECS <-- InnerAPI_Image

@enduml
